services:
  - type: web
    name: notes-backend
    env: java
    plan: free
    buildCommand: ./mvnw -B -DskipTests package
    startCommand: java -jar target/notes-api-0.0.1-SNAPSHOT.jar
    envVars:
      - key: JAVA_VERSION
        value: 17
      - key: CORS_ALLOWED_ORIGIN
        value: "https://vercel.com/arpit-vermas-projects-ab65e9dd/notes-frontend"   # later replace with your frontend domain
