services:
  - type: web
    name: notes-backend
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: CORS_ALLOWED_ORIGIN
        value: "https://notes-frontend-two-sable.vercel.app/"
